dist: bionic
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
install:
  - pip install -r requirements.txt
script:
  - CFLAGS="-Wall -Wextra" ./setup.py build
  - coverage run --source=. ./setup.py test
after_script:
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
  - codecov
# install build dependencies and enable Coverity scan
addons:
  coverity_scan:
    project:
      name: "gammu/python-gammu"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command: ./setup.py build
    branch_pattern: coverity_scan
  apt:
    packages:
    - libgammu-dev
    - libdbd-sqlite3
